# This is a config for E2B sandbox template.
# You can use template ID (ytfhp6l5zmnxinrxr783) or template name (codegenie-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codegenie-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("codegenie-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codegenie-nextjs')

team_id = "bf80777f-4f45-4d4c-bbfe-e86c2e200b07"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codegenie-nextjs"
template_id = "ytfhp6l5zmnxinrxr783"
